name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.4
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Debug environment
        run: |
          echo "Node version: $(node --version)"
          echo "npm version: $(npm --version)"
          echo "npx version: $(npx --version)"
          echo "Current directory: $(pwd)"
          echo "Files in current directory: $(ls -la)"

      # ---------- Quality gates ----------
      - name: ESLint (CI mode - allow some warnings)
        run: npm run lint:ci

      - name: TypeScript strict type-check
        run: npm run type-check:strict

      - name: Unit tests (Jest)
        run: npm test -- --ci

      - name: Test coverage
        run: npm run test:coverage
        continue-on-error: true

      # ---------- Production build ----------
      - name: Build Next.js app
        run: npm run build:no-lint
        env:
          NODE_ENV: production
          CI: true
        timeout-minutes: 10

      # ---------- Deploy (only on main, only if above succeeded) ----------
      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main' && success()
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-comment: false
          vercel-args: '--confirm'
